version: '3.8'

services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: chatapp_backend
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: iqbalpahlevi
    ports:
      - '5432:5432'
    volumes:
      - database:/var/lib/postgresql/data

  backend:
    build: .
    image: iqbalpa/chatapp_backend:latest
    ports:
      - '3000:3000'
    depends_on:
      - database
    env_file:
      - .env

volumes:
  database:
    name: chatapp-db
